# Generated by Django 3.0.7 on 2022-01-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('author', models.CharField(max_length=400, null=True)),
                ('picture', models.FileField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('pdf', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
